PKGDIR ?= ../../..
L4DIR  ?= $(PKGDIR)/../..

TARGET := example_kobject_server

SRC_CC_example_kobject_server := example_kobject_server.cc

PRIVATE_INCDIR := $(PKGDIR)/shared

include $(L4DIR)/mk/prog.mk
