PKGDIR ?= .
L4DIR  ?= $(PKGDIR)/../../../../..

# XXX compile both targets

TARGET := example_kobject_client_rust

SRC_RS := src/example_kobject_client_rust.rs

#TARGET := example_dataspace_rust
#
#SRC_RS := src/example_dataspace_rust.rs

REQUIRES_LIBS := libc_be_sig

include $(L4DIR)/mk/prog.mk
